#define BK_IMPLEMENTATION
#include <bk/fs/crt.h>
#include <bk/fs/prefix.h>
#include <bk/fs/vfs.h>
#include <bk/fs/ro.h>
#include <bk/fs/utils.h>
#include <bk/fs/mem.h>
#include <bk/stdstream.h>
#include <bk/default_allocator.h>
#include <bk/array.h>
#include <bk/printf.h>
